app:
  useFakeCustomerRepo: false

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ON_PARAM

spring:
  datasource:
    url: jdbc:h2:mem:testdb-dev-env
    driverClassName: org.h2.Driver
    username: hello
    password: goodbye
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-dev

logging:

info:
  app:
    name: Spring Boot Master Class
    description: Master Spring Boot
    version: 1.0.0
  company:
    name: Wonderful Products

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
